const S=document.querySelector('#screen'),L=document.querySelector('#screenLabel');let i=0;
const bodyTiles=Array.from({length:7},(_,x)=>`<button class="tile">BODY ${x+1}</button>`).join('');
const pages=[
['CREATE ME — FACE',`<h1>Create Me</h1><div class="box image">FACE / CAMERA<br>identity source</div><button class="btn yes">USE THIS FACE</button>`],
['CREATE ME — MEASUREMENTS',`<h1>Your measurements</h1><div class="field">HEIGHT <b>5′5″</b> ↔ cm</div><div class="field">WEIGHT <b>58 kg</b> ↔ lb</div><div class="field">BUST / WAIST / HIPS <b>38 / 31 / 37</b></div><button class="btn yes">THIS LOOKS RIGHT</button>`],
['IDENTITY GENERATING',`<h1>Creating you…</h1><div class="box image">ALBUS is doing the math...</div>`],
['CANON CONFIRMATION',`<h1>Does this resemble you?</h1><div class="box image">PERSONALIZED ROOT / CANON</div><div class="row"><button class="btn">NO</button><button class="btn yes">YES</button></div><p class="muted">NO → “Really, gurl?” → “NA-AH!” → manual correction</p>`],
['BODY SELF-SELECTION',`<h1>Which one feels like you?</h1><p class="muted">Founder visual-inspection placeholder: 7 neutral alternatives. Exact superseding presentation UI is intentionally NOT guessed.</p><div class="grid">${bodyTiles}</div><div class="row"><button class="btn">CHOOSE AGAIN</button><button class="btn yes">THIS ONE</button></div>`],
['MAIN HOME',`<div class="compact"><h1>SHALA</h1><b>MIRROR ON THE WALL</b><hr><button class="btn">EXPLORE</button><button class="btn">TREND ALERT</button><button class="btn">FAVORITES</button></div>`],
['WORKSHOP',`<h1>What are we trying on?</h1>${['CLOTHES','BAGS','SHOES','ACCESSORIES'].map(x=>`<button class="btn">${x} — TRY ME</button>`).join('')}<p class="muted">Accessories V1: HAT · GLASSES · NECKLACE — one per interaction.</p>`],
['POSE SELECTION',`<h1>Choose a Pose</h1><div class="poses">${Array.from({length:10},(_,x)=>`<button class="tile">POSE ${x+1}</button>`).join('')}</div><div class="row"><button class="btn">CHOOSE AGAIN</button><button class="btn yes">SELECT</button></div>`],
['STUDIO SELECTION',`<h1>Choose a Studio</h1><div class="studio"><div class="blue"><h2>BLUE 1170 × 844</h2>Independent pan / zoom workspace<br>centered against RED 390 × 844</div></div><div class="studios">${['Indoor Office','Indoor Living Room','Indoor Disco','Outdoor Sunny Patio','Outdoor Golden Hour','My Studio'].map(x=>`<button class="tile">${x}</button>`).join('')}</div><div class="row"><button class="btn">CHOOSE AGAIN</button><button class="btn yes">SELECT</button></div>`],
['REFERENCE',`<h1>Add Reference</h1><div class="box image">GARMENT / LOOK REFERENCE</div><button class="btn">SWAP</button><button class="btn yes">GENERATE</button>`],
['ALBUS GENERATING',`<h1>ALBUS is doing the math...</h1><div class="box image">LOCAL V1 GENERATION PLACEHOLDER</div><p class="muted">Back / accidental navigation guarded during active transformation.</p>`],
['THE REVEAL',`<h1>The Reveal</h1><div class="box image">RESULT IMAGE</div><label class="box"><input type="checkbox"> REFERENCE ○</label><button class="btn">⤓ Save to Device</button><button class="btn">♡ Favorite</button><button class="btn yes">↻ Try Another One</button>`],
['TREND ALERT',`<h1>Trend Alert</h1><div class="box image">GACHA → TREND REVEAL</div><button class="btn yes">VIEW / OPEN ↗</button><p class="muted">Google Images · new tab · return preserves reveal state</p>`],
['FAVORITES',`<h1>Favorites</h1>${[1,2,3].map(x=>`<div class="box">FAVORITE ${x}</div>`).join('')}<button class="btn">START AGAIN</button><button class="btn">NUCLEAR RESET</button>`]
];function draw(){let [n,h]=pages[i];L.textContent=n;S.innerHTML=h}document.querySelector('#back').onclick=()=>{i=(i-1+pages.length)%pages.length;draw()};document.querySelector('#next').onclick=()=>{i=(i+1)%pages.length;draw()};draw();